Add last process exit code to prompt string

diff --git a/roles/provision/tasks/dotfiles.yml b/roles/provision/tasks/dotfiles.yml
--- a/roles/provision/tasks/dotfiles.yml
+++ b/roles/provision/tasks/dotfiles.yml
@@ -65,7 +65,7 @@
         group: "{{ gid }}"
         mode: "0644"
 
-    - name: Git branch in PS1 - helper files
+    - name: Git branch in PS1 helper files
       ansible.builtin.copy:
         src: git/dotgit/
         dest: "{{ home }}/.git/"
@@ -73,7 +73,7 @@
         group: "{{ gid }}"
         mode: "0644"
 
-    - name: Git branch in PS1 - .bashrc
+    - name: Set bash prompt strings
       ansible.builtin.blockinfile:
         path: "{{ home }}/.bashrc"
         block: |
@@ -85,8 +85,29 @@
           export GIT_PS1_SHOWSTASHSTATE=1
           export GIT_PS1_SHOWUNTRACKEDFILES=1
           export GIT_PS1_SHOWUPSTREAM=1
-          export PS1="\[\e[01;32m\H \A \[\e[01;34m\]\w\[\e[38;5;204m\]\$(__git_ps1)\n\[\e[01;32m\]>\[\e[00m\] "
           export PS2="\[\e[38;5;204m\]>\[\e[00m\] "
+
+          # Set PS1
+          # Function needed to dynamically set exit code
+          __prompt_command() {
+            local EXIT_CODE="$?"
+
+            local GREEN='\[\e[01;32m\]'
+            local RED='\[\e[01;31m\]'
+            local BLUE='\[\e[01;34m\]'
+            local BRIGHT_PINK='\[\e[38;5;204m\]'
+            local NORMAL='\[\e[0m\]'
+
+            if [ $EXIT_CODE == 0 ]; then
+              PS1="$GREEN$EXIT_CODE"
+            else
+              PS1="$RED$EXIT_CODE"
+            fi
+
+            PS1="$PS1 $GREEN\H \A $BLUE\w$BRIGHT_PINK\$(__git_ps1)\n$GREEN>$NORMAL "
+          }
+
+          export PROMPT_COMMAND=__prompt_command
 
     - name: Set editor to vim
       ansible.builtin.lineinfile:
